kind: pipeline
type: docker

name: default

steps:
  - name: install-dependencies
    image: python:3.9
    commands:
      - pip install -r requirements.txt
  - name: flake8
    image: python:3.9
    commands:
      - pip install flake8
      - flake8
